### ISSUE TITLE
The application requested process termination through System.Environment.FailFast(string message).

### ISSUE THREAD

**Issue by csunkara-ipipeline** [CodeFactoryLLC/WebForms2BlazorServer#6]
Has anyone experienced out of memory errors when using this on a very large project?

I tried it multiple times and also closed everything else on my machine but it still crashes with the following error. I don't think the memory went above 75% though overall on the machine so not sure what the reason is.

Any ideas?

The application requested process termination through System.Environment.FailFast(string message).
Message: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken.SyntaxIdentifierWithTrivia.<>c.<.cctor>b__5_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.IdentifierNameSyntax..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.IdentifierNameSyntax.<>c.<.cctor>b__15_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.MemberAccessExpressionSyntax..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.MemberAccessExpressionSyntax.<>c.<.cctor>b__21_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.AssignmentExpressionSyntax..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.AssignmentExpressionSyntax.<>c.<.cctor>b__21_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ExpressionStatementSyntax..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ExpressionStatementSyntax.<>c.<.cctor>b__21_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxList.WithManyChildrenBase..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxList.WithManyChildren.<>c.<.cctor>b__0_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.BlockSyntax..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.BlockSyntax.<>c.<.cctor>b__24_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.IfStatementSyntax..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.IfStatementSyntax.<>c.<.cctor>b__33_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxList.WithManyChildrenBase..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxList.WithManyChildren.<>c.<.cctor>b__0_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.BlockSyntax..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.BlockSyntax.<>c.<.cctor>b__24_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.IfStatementSyntax..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.IfStatementSyntax.<>c.<.cctor>b__33_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxList.WithManyChildrenBase..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxList.WithManyChildren.<>c.<.cctor>b__0_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.BlockSyntax..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.BlockSyntax.<>c.<.cctor>b__24_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.MethodDeclarationSyntax..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.MethodDeclarationSyntax.<>c.<.cctor>b__45_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxList.WithManyChildrenBase..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxList.WithLotsOfChildren.<>c.<.cctor>b__0_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ClassDeclarationSyntax..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ClassDeclarationSyntax.<>c.<.cctor>b__45_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.NamespaceDeclarationSyntax..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.NamespaceDeclarationSyntax.<>c.<.cctor>b__42_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.CompilationUnitSyntax..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.CompilationUnitSyntax.<>c.<.cctor>b__27_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode.DeserializeFrom(Stream stream, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTreeFactoryServiceFactory.CSharpSyntaxTreeFactoryService.DeserializeNodeFrom(Stream stream, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Host.AbstractSyntaxTreeFactoryService.RecoverableSyntaxRoot`1.RecoverRoot(Stream stream, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Host.AbstractSyntaxTreeFactoryService.RecoverableSyntaxRoot`1.<RecoverAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Host.WeaklyCachedRecoverableValueSource`1.<GetValueAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTreeFactoryServiceFactory.CSharpSyntaxTreeFactoryService.RecoverableSyntaxTree.<GetRootAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.<GetRootAsyncCore>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Progression.SymbolContainment.<GetContainedSyntaxNodesAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Progression.ContainsChildrenGraphQuery.<GetGraphAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Progression.GraphQueryManager.<PopulateContextGraphAsync>d__14.MoveNext()
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.WatsonReporter.ReportNonFatal(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportWithoutCrashUnlessCanceledAndPropagate(System.Exception)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Progression.GraphQueryManager+<PopulateContextGraphAsync>d__14.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Progression.GraphQueryManager+<PopulateContextGraphAsync>d__14.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.Finish(Boolean)
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetException(System.Object)
   at System.Threading.Tasks.Task+WhenAllPromise`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Threading.Tasks.Task)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.Finish(Boolean)
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetException(System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetException(System.Exception)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Progression.ContainsChildrenGraphQuery+<GetGraphAsync>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.Finish(Boolean)
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetException(System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetException(System.Exception)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Progression.SymbolContainment+<GetContainedSyntaxNodesAsync>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.Finish(Boolean)
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetException(System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetException(System.Exception)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree+<GetRootAsyncCore>d__58.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.Finish(Boolean)
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetException(System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetException(System.Exception)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTreeFactoryServiceFactory+CSharpSyntaxTreeFactoryService+RecoverableSyntaxTree+<GetRootAsync>d__27.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.Finish(Boolean)
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetException(System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetException(System.Exception)
   at Microsoft.CodeAnalysis.Host.WeaklyCachedRecoverableValueSource`1+<GetValueAsync>d__15[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by sgiffinlcd** [comment]
@csunkara-ipipeline 
I am pretty sure I understand what the underlying issue is. This has to do with a performance measure we took early on when authoring this template. We chose the load the entire projects models into ram for fast processing of all steps in the project. If you could give us a bit of information about your project. 

- Number of objects in the project 
- Now much ram are you working with on your computer

This will help me work with @jhannahLCD  to give you a work around. Basically Ill work with john to give you a processing loop that loads in batches. This will slow down project processing but will keep us from hitting a ceiling on available ram.

**Comment by jhannahLCD** [comment]
@csunkara-ipipeline 
Just to be clear, was this error showing up when doing the bulk migration from the project and not a single-file migration?

**Comment by csunkara-ipipeline** [comment]
@jhannahLCD  Yes this was when doing the bulk migration. It's a very large project to try individual files and hence I tried the bulk option first.

@sgiffinlcd  The RAM I have is 16GB. There are more than 2500 aspx pages and there's more than 200 user controls.

**Comment by jhannahLCD** [comment]
@csunkara-ipipeline @sgiffinlcd 

I have identified where the problem is occurring.  It is happening in the following method:

`        /// <summary>
        /// Starts the migration process from webforms project to a blazor server project.
        /// </summary>
        /// <param name="webFormsProject">Source project to read data from.</param>
        /// <param name="blazorServerProject">Target server blazor project to inject into.</param>
        /// <param name="steps">The migration steps that are to be run.</param>
        public async Task StartMigration(VsProject webFormsProject, VsProject blazorServerProject, MigrationSteps steps)`

of the WebFormsToServerMigration class.

There is a command at line 100

'                var webFormProjectData = await webFormsProject.LoadAllProjectData();'

Who's original intent was to speed up later loading/processing of individual files.  However - on a project as large as yours it is simply running the Visual Studio app instance out of memory (Visual Studio is still limited to 4GB of memory regardless of how much you have installed on your machine).

I am in the process of altering this code, and later dependent calls, to lighten the load for very large projects like the one you are working with.

**Comment by csunkara-ipipeline** [comment]
Thank you @jhannahLCD. Looking forward to the changes :)

**Comment by csunkara-ipipeline** [comment]
Btw, I have taken up a 30 day trial of CodeFactory to try this out. I know you may be busy with other stuff but any chance the fix can be provided sooner rather than later?

**Comment by jhannahLCD** [comment]
@csunkara-ipipeline I have uploaded a partial fix to the memory problem.  I'd like you to try this again and see how much further this takes us.  There is a drawback however, the memory footprint should have come down - but the individual file performance on the aspx migrtion now takes a bit longer.

I continue to work the problem - but I am hoping that this clears the memory problem and keeps you moving forward.

-John

**Comment by csunkara-ipipeline** [comment]
Thank you John. I am trying the migration today with your change. Will update you the result.

**Comment by csunkara-ipipeline** [comment]
@jhannahLCD The migration of the project completed a bit earlier which is great.

I am going through the errors now.
A few observations 
1) If the Web Forms website project contains multiple masters in different folders, the migration only imported a single master page. I was able to clone the master to a separate folder though and then replace the layout in all the pages. Good thing is the @layout in the pages was containing the same folder structure as webforms so it was easy to replace it.
2) After the migration the dependencies appear to have disappeared. I am trying to see why has that happened now and how to reverse it.

![image](https://user-images.githubusercontent.com/63052952/107502063-19f6cf00-6b90-11eb-97dc-8688573b3414.png)

I can provide more feedback once I know more about the remaining errors.

**Comment by csunkara-ipipeline** [comment]
In fact I get the following error when converting the Master pages. Not sure what it means but may be it's because of multiple master pages.

![image](https://user-images.githubusercontent.com/63052952/107504948-eb7af300-6b93-11eb-968a-586861f7ee15.png)

**Comment by jhannahLCD** [comment]
@csunkara-ipipeline I'm glad that we got through the memory problem, that's a relief.

As for the Master pages - yes, I can see where this is an issue.  The original design was built from WebForms project that only really had a single site.master page.

The relevant code is under the WebFormsToServerMigration.Startup.cs class under the 
`        /// <summary>
        /// Migrates the site.master layout files from the source WebForms project into the \Shared folder
        /// in the Blazor target application project.
        /// </summary>
        /// <param name="webFormSiteMasterFiles">The flattened list of WebForms project objects/files</param>
        /// <param name="blazorServerProject">The target Blazor project object</param>
        /// <returns></returns>
        ///         private async Task ConvertAspxPage(VsDocument sourcePage, VsProject targetProject, VsProjectFolder targetPagesFolder, VsCSharpSource sourceCodeBehind = null)
        private async Task<string> ConvertLayoutFiles(IEnumerable<VsModel> webFormSiteMasterFiles, VsProject blazorServerProject)`

method.  I'll review in the meantime and see where the bug is.

**Comment by jhannahLCD** [comment]
@csunkara-ipipeline 

I almost missed the comment about not pulling over the code-behind.  Would you be willing to provide an example screenshot of the *.aspx file (and its associated code-behind *.aspx.cs file) for me?  It most definitely should be pulling that over as well.

**Comment by csunkara-ipipeline** [comment]
@jhannahLCD Regarding the master page here is a structure. The red portion is a folder for each client we have and their master is in that folder.

![image](https://user-images.githubusercontent.com/63052952/107535484-ad43fa80-6bb8-11eb-8fe7-e2645f55de2b.png)

**Comment by csunkara-ipipeline** [comment]
@jhannahLCD Regarding the code-behind issue here is an example. The aspx page has the markup and the code behind is in the AcceptableTerms.aspx.cs file. The code behind contains the call to the webservice to get the data and loading of the data into the controls and the button click events etc.

![image](https://user-images.githubusercontent.com/63052952/107535754-f2682c80-6bb8-11eb-8b57-23d45f0cd1dc.png)
